linters-settings:
  depguard:
    list-type: denylist
    packages:
      # logging is allowed only by logutils.Log, 
      - github.com/sqljames/goalctl/logutils
    packages-with-error-message:
      - github.com/sqljames/goalctl/logutils: "logging is allowed only by logutils"
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845

  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/sqljames/goalctl
  gomnd:
    # don't include the "operation" and "assign"
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
    ignored-functions:
      - strings.SplitN

  govet:
    check-shadowing: true
  lll:
    line-length: 180
  misspell:
    locale: US
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  enable-all: true
  disable:
    - nonamedreturns
    - gochecknoglobals
    - exhaustivestruct
    - logrlint
    - exhaustruct
    - gci
    - gofmt
    - goimports
    - gofumpt
  ##disable-all: true
  ##enable:
  ##  - asciicheck
  ##  - bidichk
  ##  - bodyclose
  ##  - containedctx
  ##  - contextcheck
  ##  - cyclop
  ##  - decorder
  ##  - depguard
  ##  - dogsled
  ##  - dupl
  ##  - durationcheck
  ##  - errchkjson
  ##  - errcheck
  ##  - errname
  ##  - errorlint
  ##  - execinquery
  ##  - exportloopref
  ##  - funlen
  ##  - gochecknoinits
  ##  - goconst
  ##  - gocritic
  ##  - gocyclo
  ##  - gofmt
  ##  - goimports
  ##  - gomnd
  ##  - goprintffuncname
  ##  - gosec
  ##  - gosimple
  ##  - govet
  ##  - ineffassign
  ##  - lll
  ##  - misspell
  ##  - nakedret
  ##  - noctx
  ##  - nolintlint
  ##  - staticcheck
  ##  - stylecheck
  ##  - typecheck
  ##  - unconvert
  ##  - unparam
  ##  - unused
  ##  - whitespace

  # don't enable:
  # - asciicheck
  # - scopelint
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - interfacer
  # - maligned
  # - nestif
  # - prealloc
  # - testpackage
  # - revive
  # - wsl

issues:
  fix: false

run:
  timeout: 5m
  skip-dirs:
    - magefiles
    - vendor/

output:
  format: json