// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlc

import (
	"database/sql"
)

type Goal struct {
	Goalid      int64          `json:"goalid"`
	Duedate     sql.NullString `json:"duedate"`
	Author      sql.NullString `json:"author"`
	Createddate string         `json:"createddate"`
	Goal        string         `json:"goal"`
	Details     string         `json:"details"`
	Priority    int64          `json:"priority"`
	Status      string         `json:"status"`
}

type GoalToLogEntry struct {
	Goalid     int64 `json:"goalid"`
	Logentryid int64 `json:"logentryid"`
}

type LogEntry struct {
	Logentryid  int64          `json:"logentryid"`
	Author      sql.NullString `json:"author"`
	Tags        sql.NullString `json:"tags"`
	Note        string         `json:"note"`
	Createddate string         `json:"createddate"`
	Notebookid  int64          `json:"notebookid"`
}

type Notebook struct {
	Notebookid int64  `json:"notebookid"`
	Name       string `json:"name"`
}
